name: ctoz
services:
  ctoz:
    cpu_shares: 90
    command: []
    container_name: CtoZ
    deploy:
      resources:
        limits:
          memory: 4106076160
        reservations:
          devices: []
    environment:
      - GIN_MODE=release
    image: ghcr.io/superjc710e/ctoz:latest
    labels:
      icon: https://github.com/SuperJC710e/ctoz/blob/main/frontend/public/icon.svg?raw=true
    ports:
      - target: 8080
        published: "18080"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/ctoz/logs
        target: /app/logs
    devices: []
    cap_add: []
    networks:
      - ctoz
    privileged: false
networks:
  ctoz:
    name: ctoz
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://github.com/SuperJC710e/ctoz/blob/main/frontend/public/icon.svg?raw=true
  index: /
  is_uncontrolled: false
  port_map: "18080"
  scheme: http
  store_app_id: CtoZ
  title:
    custom: ""
    en_us: CtoZ
